name: Run Application

on:
  workflow_dispatch:
    inputs:
      host:
        description: 'host'
        required: true
        type: string
      ssh_user_name:
        description: 'user name'
        required: true
        type: string
      ssh_port:
        description: 'ssh port'
        required: true
      shutdown_key:
        description: 'shutdown key'
        required: true
        type: string
      twitter_next_url:
        description: 'twitter next url'
        required: true
        type: string

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
    - name: Mask sensitive inputs
      run: |
        echo "::add-mask::${{ inputs.twitter_next_url }}"
        echo "::add-mask::${{ inputs.shutdown_key }}"
        echo "::add-mask::${{ inputs.ssh_user_name }}"
    - uses: actions/checkout@v7
    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: "3.13"
        cache: 'pip'
    - name: Install dependencies
      run: |
        sudo apt-get update && \
        sudo apt-get install -y --no-install-recommends libimage-exiftool-perl && \
        sudo rm -rf /var/lib/apt/lists/*
        pip3 install -r requirements.txt
    - name: Configure settings
      run: |
        wget -nv --tries=3 --retry-connrefused --timeout=10 -O download_info.json ${{ inputs.twitter_next_url }}task/download/info?key=${{ inputs.shutdown_key }}
        sed -i 's!"save_path": ""!"save_path": "twitter"!' settings.json
        sed -i 's!"down_log": false!"down_log": true!' settings.json
    - name: Run Application
      id: run_application  # 这个 id 用于后续引用 outputs
      run: |
        python3 main.py
    - name: Copy File
      uses: up9cloud/action-rsync@master
      env:
        HOST: ${{ inputs.host }}
        USER: ${{ inputs.ssh_user_name }}
        PORT: ${{ inputs.ssh_port }}
        KEY: ${{ secrets.SSH_KEY }}
        SOURCE: twitter/
        TARGET: /twitter-user
        ARGS: -avm --temp-dir=/tmp
    - name: Shutdown Server
      run: |
        echo "error_user: ${{ steps.run_application.outputs.error_user }}。"
        curl -s --request GET '${{ inputs.twitter_next_url }}task/download/shutdown?key=${{ inputs.shutdown_key }}&error_user=${{ steps.run_application.outputs.error_user }}'
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 5